version: "3"

networks:
  app-network:
    driver: bridge
services: 
 product-microservice:
  container_name: product-app
  image: product-microservice
  build: .
  ports: 
   - 8091:8091
  environment:
   MYSQL_HOST: mysqldb
   MYSQL_USER: root
   MYSQL_PASSWORD: root
   MYSQL_PORT: 3306
  depends_on:
   - mysqldb
  restart: always

   
 mysqldb:
  container_name: mysqldb
  image: mysql
  ports:
   - 3307:3306
  environment:
   MYSQL_DATABASE: productdb
   MYSQL_ROOT_PASSWORD: root
 